server:
  port: 8082
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/flightsearchapidatabase
    password: T0b3_T0b3
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    hibernate:
      access:
        type: field
      ddl-auto: update
    show-sql: true
    open-in-view: true